# Generated by Django 5.2.4 on 2025-08-21 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='variation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
